updated check for new commit step into validate-approvals

diff --git a/.github/workflows/ci_workflow.yml b/.github/workflows/ci_workflow.yml
--- a/.github/workflows/ci_workflow.yml
+++ b/.github/workflows/ci_workflow.yml
@@ -24,43 +24,45 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
-      # 새로운 커밋이 있는 경우에만 승인 상태 초기화 및 확인
+      # 원격 저장소에서 develop 브랜치의 최신 커밋 가져오기
+      - name: Fetch develop branch
+        run: git fetch origin develop:refs/remotes/origin/develop
+
+      # 새로운 커밋에 대해 승인 상태 확인
       - name: Check for New Commits
         id: check_commits
         run: |
-          git fetch origin "${{ github.event.pull_request.head.ref }}"
-          CHANGED_FILES=$(git diff --name-only "origin/${{ github.event.pull_request.head.ref }}"..."${{ github.event.pull_request.head.sha }}")
+          CHANGED_FILES=$(git diff --name-only origin/develop...${{ github.sha }})
           if [ -n "$CHANGED_FILES" ]; then
-            echo "New commits found. Resetting approvals..."
-            curl -s -X PUT \
-              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-              -H "Accept: application/vnd.github.v3+json" \
-              "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" \
-              | jq '.[] | select(.state == "APPROVED") | .id' \
-              | xargs -I {} curl -s -X DISMISS \
-                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-                -H "Accept: application/vnd.github.v3+json" \
-                "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews/{}"
-            echo "Approvals have been reset."
+            # 새로운 커밋이 있을 때만 승인 상태 확인
+            APPROVALS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+                "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" \
+                | jq '.[] | select(.state == "APPROVED")')
+            if [ -z "$APPROVALS" ]; then
+              echo "Approvals are required before merging to develop branch."
+              exit 1
+            else
+              echo "Approvals are received. Ready for merge."
+            fi
           else
-            echo "No new commits. No need to reset approvals."
+            echo "No new commits. No need to validate approvals."
           fi
 
       # 새로운 커밋에 대해 승인 상태 확인
-      - name: Check for Approval
-        id: check_approval
-        run: |
-          APPROVALS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-              "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" \
-              | jq '.[] | select(.state == "APPROVED")')
-          if [ -z "$APPROVALS" ]; then
-            echo "Approvals are required before merging to develop branch."
-            exit 1
-          else
-            echo "Approvals are received. Ready for merge."
-          fi
+      # - name: Check for Approval
+      #   id: check_approval
+      #   run: |
+      #     APPROVALS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+      #         "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" \
+      #         | jq '.[] | select(.state == "APPROVED")')
+      #     if [ -z "$APPROVALS" ]; then
+      #       echo "Approvals are required before merging to develop branch."
+      #       exit 1
+      #     else
+      #       echo "Approvals are received. Ready for merge."
+      #     fi
 
   merge-to-develop:
     name: Merge to Develop
